### ISSUE TITLE
about Implied alpha and stochastic limit order book (LOB) model

### ISSUE THREAD

**Issue by ahao1995** [joomong/HFT-Research#1]
hi sorry to bother you, I am insterested in the 3 part (Implied alpha and stochastic limit order book (LOB) model), and I can not find in .ipynb, is there any refrence about it, thanks!

**Comment by joomong** [comment]
I'm working on the file right now. I'll upload it as soon as it's completed. Thank you.

- The reference is , Alvaro Cartea´a (Buy Low Sell High: a High Frequency Trading Perspective)

**Comment by shouao** [comment]
> I'm working on the file right now. I'll upload it as soon as it's completed. Thank you.↳
> 
> * The reference is , Alvaro Cartea´a (Buy Low Sell High: a High Frequency Trading Perspective)

Hi joomong, I would be very appreciative if you could update this notebook, it's very helpful for paper reading homework in my MFE program. ❤
